### ISSUE TITLE
Dev/test functions locally - "module sieve has no attribute Metadata"

### ISSUE THREAD

**Issue by drnic** [sieve-community/examples#68]
I pulled down the repo and tried to run it locally:

```
cd youtube_downloader
python main.py
```

Gives easy fixable error:

```
Traceback (most recent call last):
  File "/Users/drnic/workspace/sievedata/examples/youtube_downloader/main.py", line 1, in <module>
    import sieve
ModuleNotFoundError: No module named 'sieve'
```

So install the `sieve` pip:

```
pip install sieve
python main.py
```

Returns new error:

```
Traceback (most recent call last):
  File "/Users/drnic/workspace/sievedata/examples/youtube_downloader/main.py", line 9, in <module>
    metadata = sieve.Metadata(
               ^^^^^^^^^^^^^^
AttributeError: module 'sieve' has no attribute 'Metadata'
```

**Comment by drnic** [comment]
Ooh, looking in main.yml CI file I see:

```
pip install https://mango.sievedata.com/v1/client_package/sievedata-0.0.1.1.2-py3-none-any.whl
```

Now we're getting somewhere:

```
python main.py
Warning: download is running on your machine. To run it remotely on Sieve, call download.run(*args).
Traceback (most recent call last):
  File "/Users/drnic/workspace/sievedata/examples/youtube_downloader/main.py", line 75, in <module>
    download("https://www.youtube.com/watch?v=AKJfakEsgy0", include_audio=True)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sieve/functions/function.py", line 301, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drnic/workspace/sievedata/examples/youtube_downloader/main.py", line 39, in download
    from pytube import YouTube
ModuleNotFoundError: No module named 'pytube'
```

```
pip install pytube
python main.py
Warning: download is running on your machine. To run it remotely on Sieve, call download.run(*args).
setting stream...
filtering stream for highest quality mp4...
Traceback (most recent call last):
  File "/Users/drnic/workspace/sievedata/examples/youtube_downloader/main.py", line 75, in <module>
    download("https://www.youtube.com/watch?v=AKJfakEsgy0", include_audio=True)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sieve/functions/function.py", line 301, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drnic/workspace/sievedata/examples/youtube_downloader/main.py", line 58, in download
    video = yt.streams.filter(adaptive=True, file_extension='mp4').order_by('resolution').desc().first()
            ^^^^^^^^^^
...
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Ideas?

**Comment by drnic** [comment]
Ooh, perhaps need pytube from github:

```
pip uninstall pytube
pip install git+https://github.com/sieve-community/pytube.git
python main.py
```

And it works! Hurray.
